### ISSUE TITLE
Change in the corrplot package breaks factorstochvol

### ISSUE THREAD

**Issue by hdarjus** [gregorkastner/factorstochvol#5]
This commit: https://github.com/taiyun/corrplot/commit/38f91b7bdf100c39d454548764279a72535530e6 breaks this line:

https://github.com/gregorkastner/factorstochvol/blob/8e0c6888485eb9525b3ff71b47db1a0a6a6922e4/R/plotting.R#L237

in the sense that `toplot` should have `colnames` and `rownames`. See changes in function `getPos.Dat` in function `corrplot`.

**Comment by hdarjus** [comment]
weird. I cannot reproduce this error now. Anyway, I added a test suite for the plotting functionality in commit 85d58f7

**Comment by gregorkastner** [comment]
Weird indeed & thanks for the tests!

**Comment by gregorkastner** [comment]
When compiling the vignette, I see it again (this is in paper-original.Rnw:941)

> corimageplot(res, these = seq(1, n, length.out = 3), plotCI = "circle",
+   plotdatedist = 2, date.cex = 1.1)
Error in PosName[, 1] <- colnames(mat)[ind[, 2]] :
  number of items to replace is not a multiple of replacement length

**Comment by hdarjus** [comment]
Thanks! That's how I discovered it actually, yes.

**Comment by gregorkastner** [comment]
Fixed in commit 32d2b995248cb805bd5789c0ade0230012985d8b
